use_frameworks!
inhibit_all_warnings!

platform :ios, '9.3'

target 'BSK_Example' do

  pod 'BSK', :path => '../'

  target 'BSK_UnitTests' do
    inherit! :search_paths

    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

end
