use_frameworks!

target 'BSK_Example' do
  pod 'BSK', :path => '../'

  target 'BSK_Tests' do
    inherit! :search_paths
	
    # Pods for testing
    pod 'Quick', '~> 1.2'
    pod 'Nimble', '~> 7.0'
  end
end
